services:
  dev-db:
    image: postgres:18
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: workoutTracker
    networks:
      - myNetwork
networks:
  myNetwork: